[tool.semantic_release]
upload_to_pypi = false
upload_to_release = false
branch = "main"
version_variable = [
    "ver.py:__version__",
]
commit_parser = [
    "semantic_release.history.emoji_parser",
    "semantic_release.history.angular_parser",
]
